default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: debug-statements
        exclude: "litestar/middleware/exceptions/middleware.py"
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
  - repo: https://github.com/provinzkraut/unasyncd
    rev: "v0.6.0"
    hooks:
      - id: unasyncd
        additional_dependencies: ["ruff"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.282"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude: "tests/openapi/typescript_converter/test_converter"
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.1"
    hooks:
      - id: prettier
        exclude: "_templates|.git"
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.0
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
        args: ["--use-tuple"]
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.17.0
    hooks:
      - id: slotscheck
        exclude: "test_*|docs"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        exclude: "test_apps|tools|docs|tests/examples|tests/docker_service_fixtures|tests/unit/test_partial"
        additional_dependencies:
          [
            polyfactory,
            aiosqlite,
            annotated_types,
            async_timeout,
            asyncmy,
            asyncpg,
            asyncpg_stubs,
            attrs,
            beanie,
            beautifulsoup4,
            brotli,
            click,
            fast-query-parsers>=1.0.2,
            fsspec,
            httpx,
            httpx_sse,
            hypothesis,
            jsbeautifier,
            mako,
            mongomock_motor,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            opentelemetry-sdk,
            oracledb,
            piccolo,
            picologging,
            psycopg,
            pydantic>=2,
            pydantic-extra-types,
            pytest,
            pytest-lazy-fixture,
            pytest-mock,
            pytest_docker,
            python-dotenv,
            python-jose,
            pytest-timeout,
            pyyaml,
            redis,
            rich,
            rich-click,
            sqlalchemy>=2.0.12,
            starlette,
            types-beautifulsoup4,
            structlog,
            types-pyyaml,
            types-redis,
            types-python-jose,
            uvicorn,
            prometheus_client,
            time-machine,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.320
    hooks:
      - id: pyright
        exclude: "test_apps|tools|docs|_openapi|tests/examples|tests/docker_service_fixtures|tests/unit/test_partial"
        additional_dependencies:
          [
            polyfactory,
            aiosqlite,
            annotated_types,
            async_timeout,
            asyncmy,
            asyncpg,
            asyncpg_stubs,
            attrs,
            beanie,
            beautifulsoup4,
            brotli,
            click,
            fast-query-parsers>=1.0.2,
            fsspec,
            httpx,
            httpx_sse,
            hypothesis,
            jsbeautifier,
            mako,
            mongomock_motor,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            opentelemetry-sdk,
            oracledb,
            piccolo,
            picologging,
            psycopg,
            pydantic>=2,
            pydantic-extra-types,
            pytest,
            pytest-lazy-fixture,
            pytest-mock,
            pytest_docker,
            python-dotenv,
            python-jose,
            pytest-timeout,
            pyyaml,
            redis,
            rich,
            rich-click,
            sqlalchemy>=2.0.12,
            starlette,
            structlog,
            types-beautifulsoup4,
            types-pyyaml,
            types-redis,
            types-python-jose,
            uvicorn,
            prometheus_client,
            time-machine,
          ]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: "v0.6.7"
    hooks:
      - id: sphinx-lint
  - repo: local
    hooks:
      - id: pypi-readme
        name: pypi-readme
        language: python
        entry: python tools/pypi_readme.py
        types: [markdown]
